### ISSUE TITLE
implement Get for book CRUD feature

### ISSUE THREAD

**Issue by kazuki0924** [kazuki0924/go-fiber-what-to-read-app#2]
### Todo

- [x] refactor SetupMigrations() in main()

- [x] refactor domain/model

- [x] refactor domain/interface/repository

- [x] implement infrastructure/repository

- [x] implement service

- [x] implement controller

- [x] refactor SetupRoutes() in main()
